/*
 * cifar10_infer.h
 *
 * Shared interface header for the CIFAR-10 DSP inference FastRPC service.
 *
 * In a full Hexagon SDK build this header is auto-generated by qaic
 * from cifar10_infer.idl.  The version here is a manual equivalent so
 * the project compiles without running the IDL compiler first.
 */

#ifndef CIFAR10_INFER_H
#define CIFAR10_INFER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/*  Return codes (standard Qualcomm AEE values)                        */
/* ------------------------------------------------------------------ */
#ifndef AEE_SUCCESS
#define AEE_SUCCESS            0
#endif
#ifndef AEE_EFAILED
#define AEE_EFAILED            1
#endif
#ifndef AEE_ENOMEMORY
#define AEE_ENOMEMORY          2
#endif
#ifndef AEE_EBADPARM
#define AEE_EBADPARM           5
#endif
#ifndef AEE_ENOTINITIALIZED
#define AEE_ENOTINITIALIZED    6
#endif

typedef int AEEResult;

/* ------------------------------------------------------------------ */
/*  Model constants                                                    */
/* ------------------------------------------------------------------ */
#define CIFAR10_IMG_SIZE       32
#define CIFAR10_NUM_CHANNELS    3
#define CIFAR10_NUM_CLASSES    10

#define CIFAR10_INPUT_FLOATS   (CIFAR10_NUM_CHANNELS * CIFAR10_IMG_SIZE * CIFAR10_IMG_SIZE)
#define CIFAR10_INPUT_BYTES    (CIFAR10_INPUT_FLOATS * (int)sizeof(float))
#define CIFAR10_OUTPUT_BYTES   (CIFAR10_NUM_CLASSES  * (int)sizeof(float))

/* ------------------------------------------------------------------ */
/*  Parameter IDs for get_param / set_param                            */
/* ------------------------------------------------------------------ */
#define CIFAR10_PARAM_IMG_SIZE       0
#define CIFAR10_PARAM_NUM_CLASSES    1
#define CIFAR10_PARAM_USE_HVX        2   /* 0 = default, 1 = HVX path   */
#define CIFAR10_PARAM_VERSION        3   /* read-only                    */

/* ------------------------------------------------------------------ */
/*  FastRPC interface functions                                        */
/* ------------------------------------------------------------------ */

/*
 * Load the model on the DSP.
 *
 *   model_path      – null-terminated file path on the device
 *                     (e.g. "/data/local/tmp/resnet18_cifar10.dlc")
 *   model_path_len  – length in bytes including the null terminator
 */
AEEResult cifar10_infer_init(const uint8_t *model_path,
                             int            model_path_len);

/*
 * Release all DSP-side model resources.
 */
AEEResult cifar10_infer_deinit(void);

/*
 * Set a runtime parameter.
 */
AEEResult cifar10_infer_set_param(int param_id, int value);

/*
 * Query a runtime parameter.
 */
AEEResult cifar10_infer_get_param(int param_id, int *value);

/*
 * Run inference on one preprocessed image.
 *
 *   input_tensor      – CHW float32 tensor as raw bytes
 *                       (3 * 32 * 32 * sizeof(float) = 12288 bytes)
 *   input_tensor_len  – size in bytes (must == CIFAR10_INPUT_BYTES)
 *   output_logits     – caller-allocated buffer for NUM_CLASSES floats
 *   output_logits_len – capacity in bytes (>= CIFAR10_OUTPUT_BYTES)
 *   output_logits_lenout – actual bytes written (CIFAR10_OUTPUT_BYTES)
 */
AEEResult cifar10_infer_process(const uint8_t *input_tensor,
                                int            input_tensor_len,
                                uint8_t       *output_logits,
                                int            output_logits_len,
                                int           *output_logits_lenout);

#ifdef __cplusplus
}
#endif

#endif /* CIFAR10_INFER_H */
