/*
 * vec_dot.h
 *
 * Shared interface header for the vector dot-product FastRPC example.
 *
 * In a full Hexagon SDK build this header is auto-generated by qaic
 * from vec_dot.idl.  The version here is a manual equivalent so the
 * project compiles without running the IDL compiler first.
 */

#ifndef VEC_DOT_H
#define VEC_DOT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/*  Return codes (standard Qualcomm AEE values)                        */
/* ------------------------------------------------------------------ */
#ifndef AEE_SUCCESS
#define AEE_SUCCESS            0
#endif
#ifndef AEE_EFAILED
#define AEE_EFAILED            1
#endif
#ifndef AEE_ENOMEMORY
#define AEE_ENOMEMORY          2
#endif
#ifndef AEE_EBADPARM
#define AEE_EBADPARM           5
#endif
#ifndef AEE_ENOTINITIALIZED
#define AEE_ENOTINITIALIZED    6
#endif

typedef int AEEResult;

/* ------------------------------------------------------------------ */
/*  Parameter IDs for get_param / set_param                            */
/* ------------------------------------------------------------------ */
#define VEC_DOT_PARAM_VEC_LEN         0   /* number of float elements per vector  */
#define VEC_DOT_PARAM_USE_HVX         1   /* 0 = scalar loop, 1 = HVX (future)   */
#define VEC_DOT_PARAM_VERSION         2   /* read-only: implementation version    */

/* ------------------------------------------------------------------ */
/*  Defaults                                                           */
/* ------------------------------------------------------------------ */
#define VEC_DOT_DEFAULT_LEN    1024

/* ------------------------------------------------------------------ */
/*  FastRPC interface functions                                        */
/* ------------------------------------------------------------------ */

/*
 * Prepare the DSP side.  Call once before any process() calls.
 */
AEEResult vec_dot_init(void);

/*
 * Release DSP resources.
 */
AEEResult vec_dot_deinit(void);

/*
 * Set a runtime parameter.
 */
AEEResult vec_dot_set_param(int param_id, int value);

/*
 * Query a runtime parameter.
 */
AEEResult vec_dot_get_param(int param_id, int *value);

/*
 * Compute the dot product of two float32 vectors on the DSP.
 *
 *   vec_a          – first  vector (float32 array as raw bytes)
 *   vec_a_len      – size in bytes  (must be N * sizeof(float))
 *   vec_b          – second vector (float32 array as raw bytes)
 *   vec_b_len      – size in bytes  (must equal vec_a_len)
 *   result         – caller-allocated buffer for one float32 result
 *   result_len     – capacity in bytes (>= sizeof(float))
 *   result_lenout  – actual bytes written (always sizeof(float) on success)
 */
AEEResult vec_dot_process(const uint8_t *vec_a,    int vec_a_len,
                          const uint8_t *vec_b,    int vec_b_len,
                          uint8_t       *result,   int result_len,
                          int           *result_lenout);

#ifdef __cplusplus
}
#endif

#endif /* VEC_DOT_H */
